use bevy::prelude::*;

use crate::{
    common::{Direction, PixelPos, TilePos},
    components::Position,
    score::Scorable,
};

pub const MAP_WIDTH: usize = 28;
pub const MAP_HEIGHT: usize = 31;
pub const TILE_SIZE: i32 = 8;

#[derive(Component, Clone, Debug, PartialEq)]
pub enum MapType {
    Wall(WallType),
    Open(OpenContent),
    GhostOnlyBarrier,
}

#[derive(PartialEq, Clone, Debug)]
pub enum OpenContent {
    None,
    Food,
    Energizer,
}

#[derive(PartialEq, Clone, Debug)]
pub enum WallType {
    Straight(Direction),
    DoubleStraight(Direction),
    DoubleCorner(Corner),
    VerticalLineInnerCorner(Corner),
    OuterCorner(Corner),
    InnerCorner(Corner),
    NestCorner(Corner),
    Inner,
    HorizontalLineInnerCornerTopRight,
    HorizontalLineInnerCornerTopLeft,
    NestEntranceLeftEdge,
    NestEntranceRightEdge,
}

#[derive(PartialEq, Clone, Debug)]
pub enum Corner {
    TopRight,
    TopLeft,
    BottomRight,
    BottomLeft,
}

#[derive(Deref, DerefMut)]
pub struct Map([[MapType; MAP_WIDTH]; MAP_HEIGHT]);

impl Map {
    const FORBIDDEN_TILES: [TilePos; 11] = [
        TilePos { x: 11, y: 13 },
        TilePos { x: 11, y: 14 },
        TilePos { x: 11, y: 15 },
        TilePos { x: 12, y: 15 },
        TilePos { x: 13, y: 15 },
        TilePos { x: 14, y: 15 },
        TilePos { x: 15, y: 15 },
        TilePos { x: 16, y: 15 },
        TilePos { x: 16, y: 14 },
        TilePos { x: 16, y: 13 },
        TilePos { x: 15, y: 13 },
    ];

    pub fn is_in_ghost_up_block_area(&self, tile_pos: &TilePos) -> bool {
        tile_pos.x >= 11 && tile_pos.x <= 16 && (tile_pos.y == 11 || tile_pos.y == 17)
    }

    pub fn in_tunnel(&self, tile_pos: &TilePos) -> bool {
        tile_pos.y == 14 && (tile_pos.x <= 5 || tile_pos.x >= 22)
    }

    pub fn get_tp_position(&self, tile_pos: &TilePos) -> Option<TilePos> {
        match (tile_pos.x, tile_pos.y) {
            (-1, 14) => Some(TilePos { x: 28, y: 14 }),
            (28, 14) => Some(TilePos { x: -1, y: 14 }),
            _ => None,
        }
    }

    /// Returns wether the tile at [pos] is a wall or not.
    /// If the position is outside of map tiles, returns true
    pub fn is_wall(&self, tile_pos: &TilePos) -> bool {
        let x = tile_pos.x as usize;
        let y = tile_pos.y as usize;

        if self
            .get_tp_position(&TilePos {
                x: x as i32,
                y: y as i32,
            })
            .is_some()
        {
            // TP Positions are walkable.
            return false;
        }

        if x >= MAP_WIDTH || y >= MAP_HEIGHT {
            return true;
        }

        match self.0[y][x] {
            MapType::Wall(_) => true,
            MapType::Open(_) => false,
            MapType::GhostOnlyBarrier => true, // TODO: Handle ghosts,
        }
    }

    pub fn get_at(&self, tile_pos: &TilePos) -> MapType {
        if tile_pos.x < 0 || tile_pos.y < 0 {
            panic!("Tile ({}, {}) out of bounds", tile_pos.x, tile_pos.y);
        }

        let x = tile_pos.x as usize;
        let y = tile_pos.y as usize;

        if x >= MAP_WIDTH || y >= MAP_HEIGHT {
            panic!("Tile ({}, {}) out of bounds", tile_pos.x, tile_pos.y);
        }

        self[y][x].clone()
    }

    pub fn get_empty_neighbours(&self, pos: &TilePos) -> Vec<(TilePos, Direction)> {
        let directions = vec![
            Direction::Up,
            Direction::Down,
            Direction::Right,
            Direction::Left,
        ];

        directions
            .into_iter()
            .map(|dir| (pos.translate(&dir), dir))
            .filter(|(p, _)| !MAP.is_wall(p))
            .filter(|(p, _)| !Map::FORBIDDEN_TILES.contains(p))
            .collect()
    }
}

pub fn spawn_map(
    commands: &mut Commands,
    asset_server: &Res<AssetServer>,
    texture_atlas_layouts: &mut ResMut<Assets<TextureAtlasLayout>>,
) {
    let texture = asset_server.load("sprites/pacman_spritesheet_2.png");
    let layout = TextureAtlasLayout::from_grid(UVec2::splat(8), 28, 31, None, None);
    let texture_atlas_layout = texture_atlas_layouts.add(layout);

    // Spawn maze
    MAP.iter().enumerate().for_each(|(row_num, row)| {
        row.iter().enumerate().for_each(|(col_num, tile)| {
            let x = col_num as i32;
            let y = row_num as i32;

            match tile {
                MapType::Wall(wall_type) => {
                    spawn_wall(commands, x, y, wall_type, &texture, &texture_atlas_layout);
                }
                MapType::GhostOnlyBarrier => {
                    spawn_ghost_only_barrier(commands, x, y, &texture, &texture_atlas_layout)
                }
                MapType::Open(open_type) => {
                    spawn_open(commands, x, y, &open_type, &texture, &texture_atlas_layout);
                }
            };
        })
    })
}

fn spawn_wall(
    commands: &mut Commands,
    x: i32,
    y: i32,
    wall_type: &WallType,
    texture: &Handle<Image>,
    texture_atlas_layout: &Handle<TextureAtlasLayout>,
) {
    let sprite_index = sprite_index_for_wall_type(wall_type);

    let tile_pos = TilePos { x, y };
    let pos: PixelPos = tile_pos.into();

    commands.spawn((
        Position(pos.clone()),
        Sprite::from_atlas_image(
            texture.clone(),
            TextureAtlas {
                layout: texture_atlas_layout.clone(),
                index: sprite_index,
            },
        ),
        Transform::from_translation(Vec3::new(pos.x as f32, -pos.y as f32, -1.0)),
    ));
}

fn spawn_ghost_only_barrier(
    commands: &mut Commands,
    x: i32,
    y: i32,
    texture: &Handle<Image>,
    texture_atlas_layout: &Handle<TextureAtlasLayout>,
) {
    let tile_pos = TilePos { x, y };
    let pos: PixelPos = tile_pos.into();

    commands.spawn((
        Position(pos.clone()),
        Sprite::from_atlas_image(
            texture.clone(),
            TextureAtlas {
                layout: texture_atlas_layout.clone(),
                index: 350,
            },
        ),
        Transform::from_translation(Vec3::new(pos.x as f32, -pos.y as f32, -1.0)),
    ));
}

fn spawn_open(
    commands: &mut Commands,
    x: i32,
    y: i32,
    open_content: &OpenContent,
    texture: &Handle<Image>,
    texture_atlas_layout: &Handle<TextureAtlasLayout>,
) {
    let (scorable, sprite_index) = match open_content {
        OpenContent::None => return,
        OpenContent::Food => (Scorable::Dot, 29),
        OpenContent::Energizer => (Scorable::Energizer, 85),
    };

    let tile_pos = TilePos { x, y };
    let pos: PixelPos = tile_pos.into();

    commands.spawn((
        Position(pos.clone()),
        Sprite::from_atlas_image(
            texture.clone(),
            TextureAtlas {
                layout: texture_atlas_layout.clone(),
                index: sprite_index,
            },
        ),
        scorable,
        Transform::from_translation(Vec3::new(pos.x as f32, -pos.y as f32, -1.0)),
    ));
}

pub fn sprite_index_for_wall_type(wall_type: &WallType) -> usize {
    match wall_type {
        WallType::Straight(Direction::Up) => 115,
        WallType::Straight(Direction::Right) => 41,
        WallType::Straight(Direction::Down) => 59,
        WallType::Straight(Direction::Left) => 42,
        WallType::DoubleStraight(Direction::Up) => 1,
        WallType::DoubleStraight(Direction::Right) => 55,
        WallType::DoubleStraight(Direction::Down) => 253,
        WallType::DoubleStraight(Direction::Left) => 28,
        WallType::DoubleCorner(Corner::TopRight) => 27,
        WallType::DoubleCorner(Corner::BottomRight) => 279,
        WallType::DoubleCorner(Corner::BottomLeft) => 252,
        WallType::DoubleCorner(Corner::TopLeft) => 0,
        WallType::VerticalLineInnerCorner(Corner::TopRight) => 727,
        WallType::VerticalLineInnerCorner(Corner::BottomRight) => 699,
        WallType::VerticalLineInnerCorner(Corner::BottomLeft) => 672,
        WallType::VerticalLineInnerCorner(Corner::TopLeft) => 700,
        WallType::HorizontalLineInnerCornerTopRight => 13,
        WallType::HorizontalLineInnerCornerTopLeft => 14,
        WallType::OuterCorner(Corner::TopRight) => 125,
        WallType::OuterCorner(Corner::BottomRight) => 58,
        WallType::OuterCorner(Corner::BottomLeft) => 61,
        WallType::OuterCorner(Corner::TopLeft) => 126,
        WallType::InnerCorner(Corner::TopRight) => 209,
        WallType::InnerCorner(Corner::BottomRight) => 271,
        WallType::InnerCorner(Corner::BottomLeft) => 260,
        WallType::InnerCorner(Corner::TopLeft) => 210,
        WallType::NestCorner(Corner::TopRight) => 458,
        WallType::NestCorner(Corner::BottomRight) => 346,
        WallType::NestCorner(Corner::BottomLeft) => 353,
        WallType::NestCorner(Corner::TopLeft) => 465,
        WallType::NestEntranceLeftEdge => 348,
        WallType::NestEntranceRightEdge => 351,
        WallType::Inner => 280,
    }
}

pub const MAP: Map = Map([
    // 0 (Upper wall)
    [
        MapType::Wall(WallType::DoubleCorner(Corner::TopLeft)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::HorizontalLineInnerCornerTopRight),
        MapType::Wall(WallType::HorizontalLineInnerCornerTopLeft),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleCorner(Corner::TopRight)),
    ],
    // 1
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 2
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 3
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 4
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 5 (Open row)
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 6
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 7
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::InnerCorner(Corner::TopRight)),
        MapType::Wall(WallType::InnerCorner(Corner::TopLeft)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 8 (Semi-open row)
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 9
    [
        MapType::Wall(WallType::DoubleCorner(Corner::BottomLeft)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::InnerCorner(Corner::BottomLeft)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::InnerCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleCorner(Corner::BottomRight)),
    ],
    // 10
    [
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::InnerCorner(Corner::TopLeft)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::InnerCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
    ],
    // 11 (Row above ghost nest)
    [
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
    ],
    // 12 (Ghost barrier row)
    [
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::NestCorner(Corner::BottomRight)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::NestEntranceLeftEdge),
        MapType::GhostOnlyBarrier,
        MapType::GhostOnlyBarrier,
        MapType::Wall(WallType::NestEntranceRightEdge),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::NestCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
    ],
    // 13 (First nest row)
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
    ],
    // 14 (Portal row)
    [
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
    ],
    // 15
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
    ],
    // 16 (Bottom wall of nest)
    [
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::NestCorner(Corner::TopRight)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::NestCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
    ],
    // 17
    [
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
    ],
    // 18
    [
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
        MapType::Wall(WallType::Inner),
    ],
    // 19
    [
        MapType::Wall(WallType::DoubleCorner(Corner::TopLeft)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::InnerCorner(Corner::TopRight)),
        MapType::Wall(WallType::InnerCorner(Corner::TopLeft)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::None),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleStraight(Direction::Up)),
        MapType::Wall(WallType::DoubleCorner(Corner::TopRight)),
    ],
    // 20 (Almost open row)
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 21
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 22
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::InnerCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::InnerCorner(Corner::TopLeft)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 23 (Second ghost eater fruit row)
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Energizer),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::None),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Energizer),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 24
    [
        MapType::Wall(WallType::VerticalLineInnerCorner(Corner::BottomLeft)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::VerticalLineInnerCorner(Corner::BottomRight)),
    ],
    // 25
    [
        MapType::Wall(WallType::VerticalLineInnerCorner(Corner::TopLeft)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::InnerCorner(Corner::TopRight)),
        MapType::Wall(WallType::InnerCorner(Corner::TopLeft)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::VerticalLineInnerCorner(Corner::TopRight)),
    ],
    // 26 (Semi-open row)
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 27
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::InnerCorner(Corner::BottomRight)),
        MapType::Wall(WallType::InnerCorner(Corner::BottomLeft)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::Straight(Direction::Right)),
        MapType::Wall(WallType::Straight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::BottomRight)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::InnerCorner(Corner::BottomRight)),
        MapType::Wall(WallType::InnerCorner(Corner::BottomLeft)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::Straight(Direction::Down)),
        MapType::Wall(WallType::OuterCorner(Corner::BottomLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 28
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::OuterCorner(Corner::TopRight)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::Straight(Direction::Up)),
        MapType::Wall(WallType::OuterCorner(Corner::TopLeft)),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 29 (Open row)
    [
        MapType::Wall(WallType::DoubleStraight(Direction::Left)),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Open(OpenContent::Food),
        MapType::Wall(WallType::DoubleStraight(Direction::Right)),
    ],
    // 30 (Bottom wall)
    [
        MapType::Wall(WallType::DoubleCorner(Corner::BottomLeft)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleStraight(Direction::Down)),
        MapType::Wall(WallType::DoubleCorner(Corner::BottomRight)),
    ],
]);
